defaults:
  - trainer: base
  - _self_
trainer:
  ddp:
    enable : True
    world_size : 2
  gradient_accum_step: 16
  dtype: torch.bfloat16
  use_amp_scaler: False
  epoch : 1
  use_cuda : True
  eval_n_sample : 1000
  save_n_sample : 1000
  val_n_sample : 1000
  compile_model:
    enable: True
    mode: default
  wandb:
    enable: True
    project_name : "llm.c-test"
    run_name : "gpt2-tinytrainer-a30-no-shuffle"
  profiler:
    enable: True
    filename: "trace.json"

